Blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.signup, name='signup-page'),
    path('loginn/', views.loginn, name='login-page'),
    path('home/', views.home, name='home'),
    path('newpost/', views.newPost, name='new-post'),
    path('mypost/', views.myPost, name='my-post'),
    path('post/<int:pk>/', views.post_detail, name='post-detail'),
    path('post/<int:pk>/edit/', views.edit_post, name='post-edit'),
    path('post/<int:pk>/delete/', views.delete_post, name='post-delete'),
    path('myprofile/', views.myProfile, name='my-profile'),
    path('update-profile/', views.update_profile, name='update-profile'),
    path('profile/delete/', views.delete_profile, name='delete-profile'),
    path('signout/', views.signout, name='signout-btn'), 
]

Blog_Application/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Blog.urls'))
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User



class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)

    def __str__(self):
        return self.user.username

Blog/forms.py
from django import forms
from .models import Post
from django.contrib.auth.models import User
from .models import UserProfile

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

class UserProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_picture']

Blog/views.py
from django.contrib.auth.models import User
from Blog import models
from .models import Post
from .forms import PostForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages  
from .models import UserProfile  
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .forms import PostForm
from .forms import UserUpdateForm, UserProfileUpdateForm
from django.shortcuts import render, get_object_or_404, redirect


def signup(request):
    if request.method == 'POST':
        name = request.POST.get('uname')
        email = request.POST.get('uemail')
        password = request.POST.get('upassword')

        # Check if the username already exists
        if User.objects.filter(username=name).exists():
            messages.error(request, "Username already taken. Please choose another.")
            return render(request, 'Blog/signup.html')

        # Check if the email already exists
        if User.objects.filter(email=email).exists():
            messages.error(request, "Email already registered. Please use a different email or login.")
            return render(request, 'Blog/signup.html')

        newUser = User.objects.create_user(username=name, email=email, password=password)
        newUser.save()

        messages.success(request, "Account created successfully! Please log in.")
        return redirect('/loginn')

    return render(request, 'Blog/signup.html')



def loginn(request):
    if request.method == 'POST':
        name = request.POST.get('uname')
        password = request.POST.get('upassword')
        profile_pic = request.FILES.get('profile_pic')  
        
        userr = authenticate(request, username=name, password=password)
        if userr is not None:
            login(request, userr)
            
            profile, created = UserProfile.objects.get_or_create(user=userr)
            if profile_pic:
                profile.profile_picture = profile_pic
                profile.save()
            
            return redirect('/home')
        else:
            return redirect('/login')

    return render(request, 'Blog/login.html')



def home(request):
    # Order the posts list by 'date_posted' in descending order (most recent posts first)
    posts_list = Post.objects.all().order_by('-date_posted')
    paginator = Paginator(posts_list, 5)  # Show 5 posts per page

    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)

    context = {
        'posts': posts
    }
    return render(request, 'Blog/home.html', context)


def newPost(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        npost = models.Post(title=title, content=content, author=request.user)
        npost.save()
        return redirect('/home')
    
    return render(request, 'Blog/newpost.html')


def myPost(request):
    context = {
        'posts': Post.objects.filter(author= request.user)
    }
    return render(request, 'Blog/mypost.html', context)


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)  
    context = {
        'post': post
    }
    return render(request, 'Blog/post_detail.html', context)

@login_required
def edit_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    # Only the author can edit the post
    if post.author != request.user:
        return redirect('home')

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('post-detail', pk=post.pk)  # redirect to post-detail
    else:
        form = PostForm(instance=post)

    return render(request, 'Blog/postforms.html', {'form': form, 'post': post})




@login_required
def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    # Only the author can delete the post
    if post.author != request.user:
        messages.error(request, "You are not authorized to delete this post.")
        return redirect('home')

    if request.method == 'POST':
        post.delete()
        messages.success(request, "Post has been deleted successfully.")
        return redirect('home')

    return render(request, 'Blog/postdelete.html', {'post': post})



def myProfile(request):
    return render(request, 'Blog/myprofile.html')


@login_required
def update_profile(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = UserProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile has been updated successfully!')
            return redirect('my-profile')  
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = UserProfileUpdateForm(instance=request.user.userprofile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }

    return render(request, 'Blog/update_profile.html', context)


@login_required
def delete_profile(request):
    if request.method == 'POST':
        user = request.user
        user.delete()
        messages.success(request, 'Your profile has been successfully deleted.')
        return redirect('home')

    return render(request, 'Blog/delete_profile_confirm.html')


def signout(request):
    logout(request)
    return redirect('/loginn')

Blog/templates/Blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        .custom-container {
            max-width: 1450px;

        }
    </style>
    <title>Blog</title>
</head>

<body>
    <div class="container custom-container">

        {% block content %}{% endblock %}

    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

Blog/templates/Blog/delete_profile_confirm.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="my-4 text-center">Delete Profile</h2>
            <p class="text-center">Are you sure you want to delete your profile? This action cannot be undone.</p>
            
            <form method="POST">
                {% csrf_token %}
                <div class="text-center">
                    <button type="submit" class="btn btn-danger">Yes, Delete My Profile</button>
                    <a href="{% url 'my-profile' %}" class="btn btn-secondary">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Blog/templates/Blog/editpost.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container custom-container">
    <h1>Edit Post</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Update Post</button>
        <a href="{% url 'post-detail' form.instance.id %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

Blog/templates/Blog/home.html
{% extends 'blog/base.html' %}
{% block content %}
{% load static %}
<div class="container custom-container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light w-100">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li><a href="/home"><img class="w-50" src="{% static 'image\blogs (1).jpg' %}" alt=""></a></li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <div class="dropdown">
                    <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Profile
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="/myprofile">My Profile</a>
                        <a class="dropdown-item" href="/newpost">New Post</a>
                        <a class="dropdown-item" href="/mypost">My Posts</a>
                        <a class="dropdown-item" href="/signout">Sign Out</a>
                    </div>
                </div>
            </form>
        </div>
    </nav>

    <br><br>
    <div class="container custom-container" style="max-width: 1350px;">
        <!-- Loop through posts -->
        {% for post in posts %}
        <article class="media content-section">
            <div class="media-body" style="border: 1px solid black; padding: 23px; margin-bottom: 10px;">
                <div class="article-metadata">
                    <h1 class="text-uppercase" style="text-align:left;float:left; color: #000000;">{{ post.author }}</h1>
                    <h5 style="text-align:right;float:right;">{{ post.date_posted|date:"F d, Y" }}</h5>
                    <hr style="clear:both;" />
                </div>
                <h3>{{ post.title }}</h3>
                <p class="article-content">{{ post.content|truncatewords:30 }}</p> 
                <a href="{% url 'post-detail' post.id %}">Read more</a> 
                <br><br>
            </div>
        </article>
        {% empty %}
        <p>No posts available.</p>
        {% endfor %}
    </div>

    <!-- Pagination -->
    <div class="pagination justify-content-center">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if posts.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a></li>
                {% endif %}

                <li class="page-item disabled">
                    <span class="page-link">Page {{ posts.number }} of {{ posts.paginator.num_pages }}</span>
                </li>

                {% if posts.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ posts.paginator.num_pages }}">Last &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

Blog/templates/Blog/login.html
{% extends 'blog/base.html' %}
{% block content %}
{% load static %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <br><br><br><br>
            <div class="card my-5" style="background-color:#F0F8FF;">

                <form class="card-body cardbody-color p-lg-5"  method="post">
                    {% csrf_token %}
                    <div class="text-center">
                        <img src="{% static 'image/logo.jpg'%}"
                            class="img-fluid profile-image-pic img-thumbnail rounded-circle my-3" width="200px"
                            alt="profile">
                    </div>

                    {% if messages %}
                <div class="mt-3">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} text-center">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

                    <div class="mb-3">
                        <input type="text" class="form-control" id="Username" name="uname" aria-describedby="emailHelp"
                            placeholder="Name">
                    </div>
                    <div class="mb-3">
                        <input type="password" class="form-control" id="password" name="upassword" placeholder="password">
                    </div>
                    <div class="text-center"><button type="submit" class="btn btn-color px-5 mb-5 w-100" value="login">Login</button>
                    </div>
                    <div id="emailHelp" class="form-text text-center mb-5 text-dark">Not
                        Registered? <a href="/" class="text-dark fw-bold"> Create an
                            Account</a>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

{% endblock %}

Blog/templates/Blog/mypost.html
{% extends 'blog/base.html' %}
{% block content %}
{% load static %}
<div class="container custom-container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light w-100">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto ">
                <li><a href="/home"><img class="w-50 " src="{% static 'image\blogs (1).jpg' %}" alt=""></a></li>

            </ul>
            <form class="form-inline my-2 my-lg-0">
                <div class="dropdown">
                    <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Profile
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="/home">Home</a>
                        <a class="dropdown-item" href="/newpost">New Post</a>
                        <a class="dropdown-item" href="/mypost">My Posts</a>
                        <a class="dropdown-item" href="/signout">Sign Out</a>
                    </div>
                </div>
            </form>
        </div>

    </nav>
    <br><br>
    <div class="container">

    </div>
    <br>
    <div class="container custom-container" style="max-width: 1350px; ">
        <h1>My Posts </h1>
        {% for post in posts %}
        <article class="media content-section">

            <div class="media-body" style="border: 1px solid black; padding: 23px; margin-bottom: 10px;">

                <div class="article-metadata">
                    <h2 class="text-uppercase" style="text-align:left;float:left; color: #000000;">{{ post.author }}</h2>
                    <h5 style="text-align:right;float:right;">{{ post.date_posted|date:"F d, Y" }}</h5>
                    <hr style="clear:both;" />

                </div>
                <h3>{{ post.title }}</h3>
                <p class="article-content">{{ post.content }}</p>
                <br><br>
            </div>
        </article>
        {% endfor %}
    </div>
</div>

{% endblock %}

Blog/templates/Blog/myprofile.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card my-5">
                <div class="card-header text-center">
                    <h4>My Profile</h4>
                    {% if messages %}
                <div class="mt-3">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} text-center">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
                </div>
                <div class="card-body text-center">
                    <div class="mb-3">
                        {% if user.userprofile.profile_picture %}
                            <img src="{{ user.userprofile.profile_picture.url }}" class="img-thumbnail rounded-circle" width="150px" alt="Profile Picture">
                        {% else %}
                            <img src="{% static 'image/logo.jpg' %}" class="img-thumbnail rounded-circle" width="150px" alt="Default Profile Picture">
                        {% endif %}
                    </div>
                    
                    <h5>Username: {{ user.username }}</h5>
                    <h5>Email: {{ user.email }}</h5>

                    <div class="mt-4">
                        <a href="{% url 'update-profile' %}" class="btn btn-primary">Edit Profile</a>
                        <a href="{% url 'delete-profile' %}" class="btn btn-danger">Delete Profile</a>
                        <a href="/home" class="btn btn-primary">Back To Home</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Blog/templates/Blog/newpost.html
{% extends 'blog/base.html' %}
{% block content %}
{% load static %}
<div class="container custom-container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light w-100">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto ">
                <li><a href="/home"><img class="w-50 " src="{% static 'image\blogs (1).jpg' %}" alt=""></a></li>

            </ul>
            <form class="form-inline my-2 my-lg-0">
                <div class="dropdown">
                    <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Profile
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="/home">Home</a>
                        <a class="dropdown-item" href="/newpost">New Post</a>
                        <a class="dropdown-item" href="/mypost">My Posts</a>
                        <a class="dropdown-item" href="/signout">Sign Out</a>
                    </div>
                </div>
            </form>
        </div>
    </nav>
    <form method="post">
        {% csrf_token %}
        <div class="container custom-container " style="max-width: 1250px;">
            <br><br>
            <h1 class="fw-bolder"> Make a new post.</h1>
            <hr><br>
            <div class="mb-3">
                <h3><label for="exampleInputEmail1" class="form-label">Heading/Title</label></h3>
                <input type="text" class="form-control" id="exampleInputText" aria-describedby="emailHelp" name="title">
            </div>
            <div class="form-group">
                <h3><label for="exampleFormControlTextarea3">Content</label></h3>
                <textarea class="form-control" id="exampleFormControlTextarea3" rows="7" name="content"></textarea>
            </div>
            <input class="btn btn-primary" type="submit" value="Submit">
        </div>
    </form>
</div>

{% endblock %}

Blog/templates/Blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container custom-container">
    <h1 class="text-uppercase">{{ post.title }}</h1>
    <p class="text-muted">by {{ post.author }} on {{ post.date_posted|date:"F d, Y" }}</p>
    <hr>
    <p>{{ post.content }}</p>
    <hr>

    {% if user == post.author %}
        <a href="{% url 'post-edit' post.id %}" class="btn btn-secondary">Edit Post</a>
    {% endif %}

    {% if user == post.author %}
        <a href="{% url 'post-delete' post.pk %}" class="btn btn-secondary">Delete Post</a>
    {% endif %}

    <a href="{% url 'home' %}" class="btn btn-secondary">Back to Home</a>
</div>
{% endblock %}

Blog/templates/Blog/postdelete.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">
    <h2 class="text-center">Are you sure you want to delete the post?</h2>
    <p class="text-center"><strong>{{ post.title }}</strong></p>

    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, Delete</button>
        <a href="{% url 'post-detail' post.pk %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

Blog/templates/Blog/postforms.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">
    <h2 class="text-center">
        {% if post.pk %}
            Edit Post: {{ post.title }}
        {% else %}
            Create New Post
        {% endif %}
    </h2>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">
            {% if post.pk %}Update{% else %}Create{% endif %}
        </button>
    </form>

    {% if post.pk %}
    <a href="{% url 'post-detail' post.pk %}" class="btn btn-secondary">Cancel</a>
    {% endif %}
</div>
{% endblock %}

Blog/templates/Blog/signup.html
{% extends 'blog/base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <br><br><br><br>
            <div class="card my-5" style="background-color:#F0F8FF;">

                {% if messages %}
                    <div class="mb-3">
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} text-center">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
                
                <form class="card-body cardbody-color p-lg-5" method="post">
                    {% csrf_token %}
                    <div class="text-center">
                        <h2>Create An Account</h2>
                    </div>
                    <br>
                    <div class="mb-3">
                        <input type="text" class="form-control" id="Username" name="uname" aria-describedby="emailHelp"
                            placeholder="Your Name" required>
                    </div>
                    <div class="mb-3">
                        <input type="email" class="form-control" id="email" name="uemail" aria-describedby="emailHelp"
                            placeholder="Your Email" required>
                    </div>
                    <div class="mb-3">
                        <input type="password" class="form-control" id="password" name="upassword"
                            placeholder="Password" required>
                    </div>
                    <br>
                    <div class="text-center">
                        <button type="submit" class="btn btn-color px-5 mb-5 w-100">Sign Up</button>
                    </div>
                    <div id="emailHelp" class="form-text text-center mb-5 text-dark">
                        Already have an account? 
                        <a href="loginn" class="text-dark fw-bold">Login here</a>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

{% endblock %}

Blog/templates/Blog/update_profile.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h2 class="my-4">Update Profile</h2>
            
            {% if messages %}
                <div class="mt-3">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} text-center">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_username">Username</label>
                    {{ user_form.username }}
                </div>
                <div class="form-group">
                    <label for="id_email">Email</label>
                    {{ user_form.email }}
                </div>
                <div class="form-group">
                    <label for="id_profile_picture">Profile Picture</label><br>
                    {% if request.user.userprofile.profile_picture %}
                        <img src="{{ request.user.userprofile.profile_picture.url }}" width="150" height="150" class="rounded-circle mb-2">
                    {% endif %}
                    {{ profile_form.profile_picture }}
                </div>
                
                <button type="submit" class="btn btn-primary">Update Profile</button>
                <a href="/home" class="btn btn-primary">Back To Home</a>

            </form>
        </div>
    </div>
</div>
{% endblock %}